/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acabra_robot_ImprovedBot */

#ifndef _Included_com_acabra_robot_ImprovedBot
#define _Included_com_acabra_robot_ImprovedBot
#ifdef __cplusplus
extern "C" {
#endif
#undef com_acabra_robot_ImprovedBot_MAX_DELAY
#define com_acabra_robot_ImprovedBot_MAX_DELAY 60000L
/*
 * Class:     com_acabra_robot_ImprovedBot
 * Method:    getKeyboardLanguage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_acabra_robot_ImprovedBot_getKeyboardLanguage
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
